// <auto-generated />
namespace ForumSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class post_model_change_new22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_model_change_new22));
        
        string IMigrationMetadata.Id
        {
            get { return "201612061230228_post_model_change_new22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
